spring.application.name=log-ingestion-service
server.port=9067
server.servlet.context-path=/log-ingestion-service

spring.datasource.url=jdbc:postgresql://localhost:5432/log_inventory
spring.datasource.username=postgres
spring.datasource.password=Lipu@9938
spring.datasource.driver-class-name=org.postgresql.Driver

initial.analyze.data.fetch.limit=15
number.peak.hours.data.fetch.limit=5

#cors config
cors.allowed.http.methods=ACL, CANCELUPLOAD, CHECKIN, CHECKOUT, COPY, DELETE, GET, HEAD, LOCK, MKCALENDAR, MKCOL, MOVE, OPTIONS, POST, PROPFIND, PROPPATCH, PUT, REPORT, SEARCH, UNCHECKOUT, UNLOCK, UPDATE, VERSION-CONTROL
cors.allowed.http.headers=Origin, X-Requested-With, Content-Type, Accept, Key, Authorization, TransactionId,locale,X-XSRF-TOKEN,X-Client-Type,X-Device-Fingerprint,X-Ip-Address,Current-Fetched-Time-Stamp
cors.allowed.client.origins= http://localhost:4300
cors.allowed.http.exposed.headers=Current-Fetched-Time-Stamp

log.user.ip.stack.base.uri=https://api.ipstack.com/{clientIp}
log.user.ip.stack.uri.access.key=8842912cdabab4df175ae1682ffda9c7

auth.public.uri.access.key=12259faf-c5c5-44cb-84d9-811e433b7112

#validate incoming jwt
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/logmanager
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/logmanager/protocol/openid-connect/certs

#kafka kafka properties
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=log-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.log.ingestion.log_ingestion_service.dto.LogRequestDto
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.properties.spring.json.use.type.headers=false
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

#kafka producer property
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.retry.backoff.ms=500
spring.kafka.producer.properties.request.timeout.ms=3000
spring.kafka.producer.properties.delivery.timeout.ms=10000

#elastic search properties
spring.elasticsearch.uris=http://localhost:9200

api.key.cache.name=tenant-cache